# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b25ce0186e3d0b6335b6befdbb827dd07f9be1281e26ff9aea075af2345e59362322e762188837ecf31ddf9e2bcf4e5b9c0f285787e001f6815dd17ca33b1ff

test:
  secret_key_base: 370d313e77cb95f1b88570fb5a917effabff308dc903bf9e6347235016dab41ec86da484b0e2f6556821f6993a8e03a53e76e4f434063151ee2a379abb7e0609

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
